/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tllr.visao;

import com.sun.org.apache.bcel.internal.generic.TABLESWITCH;
import com.tllr.controle.IMarcaControle;
import com.tllr.controle.MarcaControle;
import com.tllr.imagensnatabela.JTableRenderer;
import com.tllr.modelos.Marca;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class CadastroMarcas extends javax.swing.JFrame {
 
 IMarcaControle marcaControle = new MarcaControle();              
 InclusaoMarcas chamar = new InclusaoMarcas(this, rootPaneCheckingEnabled);
 

     
    public CadastroMarcas() {
        initComponents();
       
        try{
        marcaControle.seNaoExistirArquivo();
        marcaControle.seNaoExistirId();
        }catch(Exception e){
            
        }
        ImageIcon icon = new ImageIcon("./src/Imagens/ImageAnimacoes/marcaInclusao.gif");
        jTextFieldIdentificador.setEnabled(true);
        jTextFieldUrl.setEnabled(true);
        setLocationRelativeTo(null);
        try {
            imprimirDadosNaGrid(marcaControle.listagem());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelfundo = new javax.swing.JPanel();
        jLabelBotaoBuscar = new javax.swing.JLabel();
        jLabelIdentificador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelBotaoIncluir = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMarcas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanelTopo = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelBotaoAlterar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        jPanelfundo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelfundo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanelfundoKeyTyped(evt);
            }
        });
        jPanelfundo.setLayout(null);

        jLabelBotaoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botao buscar normal.png"))); // NOI18N
        jLabelBotaoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseMoved(evt);
            }
        });
        jLabelBotaoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseExited(evt);
            }
        });
        jPanelfundo.add(jLabelBotaoBuscar);
        jLabelBotaoBuscar.setBounds(550, 320, 93, 43);

        jLabelIdentificador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelIdentificador.setText("Identificador");
        jPanelfundo.add(jLabelIdentificador);
        jLabelIdentificador.setBounds(30, 190, 86, 20);
        jPanelfundo.add(jLabel2);
        jLabel2.setBounds(1622, 228, 123, 0);

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDescricao.setText("Descrição");
        jPanelfundo.add(jLabelDescricao);
        jLabelDescricao.setBounds(160, 190, 65, 20);

        jLabelBotaoIncluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botao incluir normal.png"))); // NOI18N
        jLabelBotaoIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoIncluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseMoved(evt);
            }
        });
        jLabelBotaoIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseExited(evt);
            }
        });
        jPanelfundo.add(jLabelBotaoIncluir);
        jLabelBotaoIncluir.setBounds(20, 320, 90, 40);

        jLabelUrl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUrl.setText("URL");
        jPanelfundo.add(jLabelUrl);
        jLabelUrl.setBounds(30, 250, 26, 20);

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelfundo.add(jLabelLogo);
        jLabelLogo.setBounds(740, 210, 70, 60);

        jTableMarcas.setAutoCreateRowSorter(true);
        jTableMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descricao", "Url", "Logo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMarcas.setRowHeight(50);
        jTableMarcas.setUpdateSelectionOnSort(false);
        jTableMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMarcasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMarcas);
        if (jTableMarcas.getColumnModel().getColumnCount() > 0) {
            jTableMarcas.getColumnModel().getColumn(3).setCellRenderer(new JTableRenderer());
        }

        jPanelfundo.add(jScrollPane1);
        jScrollPane1.setBounds(0, 370, 910, 210);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("BOTÃO ALTERAR");
        jPanelfundo.add(jLabel9);
        jLabel9.setBounds(1400, 637, 95, 16);

        jPanelTopo.setBackground(new java.awt.Color(0, 0, 51));

        jLabelEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/designed2.png"))); // NOI18N

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastro de veículos");

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(846, Short.MAX_VALUE))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelfundo.add(jPanelTopo);
        jPanelTopo.setBounds(0, 0, 1739, 130);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("BOTÃO ATUALIZAR");
        jPanelfundo.add(jLabel10);
        jLabel10.setBounds(1252, 637, 109, 16);

        jLabelBotaoAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botaoalterar.png"))); // NOI18N
        jLabelBotaoAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoAlterar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseMoved(evt);
            }
        });
        jLabelBotaoAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseExited(evt);
            }
        });
        jPanelfundo.add(jLabelBotaoAlterar);
        jLabelBotaoAlterar.setBounds(130, 320, 90, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/borda.png"))); // NOI18N
        jPanelfundo.add(jLabel3);
        jLabel3.setBounds(730, 190, 100, 100);

        jLabelLogo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelLogo1.setText("Logo");
        jPanelfundo.add(jLabelLogo1);
        jLabelLogo1.setBounds(750, 150, 60, 32);

        jButton2.setBackground(new java.awt.Color(21, 21, 88));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/curva-de-seta-apontando-para-a-esquerda.png"))); // NOI18N
        jButton2.setText("Modelos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelfundo.add(jButton2);
        jButton2.setBounds(30, 140, 100, 30);

        jButton3.setBackground(new java.awt.Color(21, 21, 88));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/casa (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelfundo.add(jButton3);
        jButton3.setBounds(140, 140, 30, 30);

        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });
        jTextFieldDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyTyped(evt);
            }
        });
        jPanelfundo.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(160, 220, 380, 22);

        jTextFieldIdentificador.setEditable(false);
        jTextFieldIdentificador.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelfundo.add(jTextFieldIdentificador);
        jTextFieldIdentificador.setBounds(30, 220, 107, 22);

        jTextFieldUrl.setEditable(false);
        jTextFieldUrl.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUrl.setToolTipText("<html>\n<div><h3>Clique aqui, ou no botão buscar para escolher uma imagem</h3>\n</html>");
        jTextFieldUrl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUrlMouseClicked(evt);
            }
        });
        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });
        jPanelfundo.add(jTextFieldUrl);
        jTextFieldUrl.setBounds(30, 270, 506, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelfundo, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelfundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void imprimirDadosNaGrid(ArrayList<Marca> listaDeMarcas) {
        try {

            DefaultTableModel model = (DefaultTableModel) jTableMarcas.getModel();
            //Limpa a tabela 
            Collections.sort(listaDeMarcas);
            model.setNumRows(0);
            Iterator<Marca> lista = listaDeMarcas.iterator();               

            while (lista.hasNext()) {
                String[] saida = new String[3];
                Marca aux = lista.next();
                saida[0] = aux.getId() + "";
                saida[1] = aux.getDescricao();
                saida[2] = aux.getUrl();
                
                //Incluir nova linha na Tabela
                model.addRow(saida);
                
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }
 
    private void jLabelBotaoBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseMoved
        jLabelBotaoBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscarencima.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);
    }//GEN-LAST:event_jLabelBotaoBuscarMouseMoved

    private void jLabelBotaoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseClicked
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscarclicado.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);
        try {

            JFileChooser fc = new JFileChooser("./src/Imagens/logos");
            File workingDirectory = new File("./src/Imagens/logos");
            fc.setCurrentDirectory(workingDirectory);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivologo = fc.getSelectedFile();
            String nomeDoArquivo = "./src/Imagens/logos/";
            String nomeFinal = nomeDoArquivo + arquivologo.getName();
            jTextFieldUrl.setText(nomeFinal);
            ImageIcon logo = new ImageIcon(nomeFinal);
             logo.setImage(logo.getImage().getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), 1));
              jLabelLogo.setIcon(logo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this,"Nenhum arquivo selecionado");
        }
    }//GEN-LAST:event_jLabelBotaoBuscarMouseClicked

    private void jLabelBotaoBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseExited
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscar.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);
    }//GEN-LAST:event_jLabelBotaoBuscarMouseExited

    private void jLabelBotaoIncluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseMoved
        jLabelBotaoIncluir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluirencima.png");
        jLabelBotaoIncluir.setIcon(iconeIncluirMouse);

    }//GEN-LAST:event_jLabelBotaoIncluirMouseMoved

    private void jLabelBotaoIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseClicked
        ImageIcon iconlogo = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluirclicado.png");
        jLabelBotaoIncluir.setIcon(iconlogo);
        try {
            File path = new File(jTextFieldUrl.getText());
            String logo  = "./src/Imagens/logos/" + path.getName();

            Marca objeto = new Marca(0, jTextFieldDescricao.getText(), logo);
            marcaControle.nada(objeto);
            marcaControle.semFoto(objeto);
            marcaControle.mesmaFoto(objeto);
          
            marcaControle.incluir(objeto);
            chamar.setVisible(true);
            timer.setRepeats(false);
            timer.start();
            jTextFieldDescricao.setText("");
            jTextFieldUrl.setText("");
            jLabelLogo.setIcon(null);
            jTextFieldIdentificador.setText("");
            imprimirDadosNaGrid(marcaControle.listagem());
            
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jLabelBotaoIncluirMouseClicked

    private void jLabelBotaoIncluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseExited
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluir.png");
        jLabelBotaoIncluir.setIcon(iconeIncluirMouse);
    }//GEN-LAST:event_jLabelBotaoIncluirMouseExited

    private void jTableMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMarcasMouseClicked
        jTextFieldIdentificador.setText(jTableMarcas.getValueAt(jTableMarcas.getSelectedRow(), 0).toString());
        jTextFieldDescricao.setText(jTableMarcas.getValueAt(jTableMarcas.getSelectedRow(), 1).toString());
        jTextFieldUrl.setText(jTableMarcas.getValueAt(jTableMarcas.getSelectedRow(), 2).toString());
        String nome = jTextFieldUrl.getText();
        ImageIcon logo = new ImageIcon(nome);
        logo.setImage(logo.getImage().getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), 1));
        jLabelLogo.setIcon(logo);
    }//GEN-LAST:event_jTableMarcasMouseClicked

    private void jLabelBotaoAlterarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseMoved
        jLabelBotaoAlterar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterarencima.png");
        jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterarMouseMoved

    private void jLabelBotaoAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseClicked
             ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterarclicado.png");
                jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
           
        if(jTableMarcas.getSelectedRow() != -1){
        try {
                Marca objetoAlterar = new Marca(Integer.parseInt(jTextFieldIdentificador.getText()), jTextFieldDescricao.getText(), jTextFieldUrl.getText());
             
                marcaControle.alterar(objetoAlterar);
                imprimirDadosNaGrid(marcaControle.listagem());
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else{
              JOptionPane.showMessageDialog(this, "Só é possível alterar uma marca válida");
        }
           
    }//GEN-LAST:event_jLabelBotaoAlterarMouseClicked

    private void jLabelBotaoAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseExited
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterar.png");
        jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterarMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadastroModelos chamar = new CadastroModelos();
        this.dispose();
        chamar.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanelfundoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelfundoKeyTyped
        
        
    }//GEN-LAST:event_jPanelfundoKeyTyped

    private void jTextFieldDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyTyped
        char e = evt.getKeyChar();

        if (!Character.isLetter(e)) {
            evt.consume();
        }

        if (Character.isLowerCase(e)) {
            evt.setKeyChar(Character.toUpperCase(e));
        }
    }//GEN-LAST:event_jTextFieldDescricaoKeyTyped

    private void jTextFieldUrlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUrlMouseClicked
        try {

            JFileChooser fc = new JFileChooser("./src/Imagens/imagesModelo");
            File workingDirectory = new File("./src/Imagens/imagesModelo");
            fc.setCurrentDirectory(workingDirectory);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivologo = fc.getSelectedFile();
            File arquivopasta = fc.getCurrentDirectory();
            String nomeDoArquivo = "./src/Imagens/logos/";
            String nomeFinal = nomeDoArquivo + arquivologo.getName();
            jTextFieldUrl.setText(nomeFinal);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo +arquivopasta.getName()+"/"+ arquivologo.getName());
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), 1));
            jLabelLogo.setIcon(iconLogo);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Nenhum arquivo selecionado");
        }
    }//GEN-LAST:event_jTextFieldUrlMouseClicked

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed

    }//GEN-LAST:event_jTextFieldUrlActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed
    Timer timer = new Timer(2500, new ActionListener(){
    public void actionPerformed(ActionEvent evt) {
        chamar.dispose();
    }
});

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBotaoAlterar;
    private javax.swing.JLabel jLabelBotaoBuscar;
    private javax.swing.JLabel jLabelBotaoIncluir;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JPanel jPanelfundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMarcas;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
