/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tllr.visao;

import com.tllr.controle.CategoriaControle;
import com.tllr.controle.ICategoriaControle;
import com.tllr.controle.IModeloControle;
import com.tllr.controle.IVeiculoControle;
import com.tllr.controle.ModeloControle;
import com.tllr.controle.VeiculoControle;
import com.tllr.enums.Situacao;
import java.awt.Cursor;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static jdk.vm.ci.common.InitTimer.timer;
import com.tllr.enums.Combustivel;
import com.tllr.enums.VeiculoTipo;
import com.tllr.modelos.Categoria;
import com.tllr.modelos.Modelo;
import com.tllr.modelos.Veiculo;
import javax.swing.DefaultComboBoxModel;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class CadastroVeiculo extends javax.swing.JFrame {
    IVeiculoControle objetoVeiculo = new VeiculoControle();
    ICategoriaControle categoria = new CategoriaControle();
    IModeloControle modelo = new ModeloControle();
   
    /**
     * Creates new form CadastroVeiculo
     */
    public CadastroVeiculo() {
        
        initComponents();
        jComboBoxSituacao.setEnabled(false);
        setBounds(0,0,920,700);
        carregarComboBox();
        jComboBoxSituacao.setSelectedIndex(1);

        setLocationRelativeTo(null);
         try {
            ArrayList<Categoria> lista = categoria.listagem();
            int tamanho = lista.size();
            String[] relacaoMarcas = new String[tamanho];
            for (int i = 0; i < lista.size(); i++) {
                relacaoMarcas[i] = lista.get(i).getDescricao();
                jComboBoxCategoria.addItem(relacaoMarcas[i]);
            }
            ArrayList<Modelo> listaModelos = modelo.listagemModelo();
            int tamanho2 = listaModelos.size();
            String[] relacaoModelos = new String[tamanho2];
            for(int b = 0; b < listaModelos.size(); b++){
                relacaoModelos[b] = listaModelos.get(b).getDescricao();
                jComboBoxModelos.addItem(relacaoModelos[b]);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Categoria não existe");
        }
        try {
            imprimirDadosNaGrid(objetoVeiculo.listagemVeiculo());
        } catch (Exception ex) {
            Logger.getLogger(CadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
   public void imprimirDadosNaGrid(ArrayList<Veiculo> listaDeVeiculos) {
        DefaultTableModel model = (DefaultTableModel) jTableVeiculo.getModel();
        model.setNumRows(0);
        Iterator<Veiculo> lista = listaDeVeiculos.iterator();
        try {
            while (lista.hasNext()) {
                String[] saida = new String[14];
                Veiculo aux = lista.next();
                saida[0] = "" + aux.getId();
                saida[1] = aux.getPlaca();
                saida[2] = aux.getRenavam() + "";
                saida[3] =aux.getPrecoCompra() + "";
                saida[4] =aux.getPrecoVenda()+ "";
                saida[5] =aux.getAnoDeFabricacao()+ "";
                saida[6] =aux.getAnoModelo()+ "";
                saida[7] =aux.getCombustivel() + "";
                saida[8] =aux.getQuilometragem()+ "";
                saida[9] =aux.getTipoVeiculo()+ "";
                saida[10] =aux.getSituacao()+ "";
                saida[11] = aux.getCategoria().getDescricao();
                saida[12] = aux.getModelo().getDescricao();
                saida[13] = modelo.buscar(aux.getModelo().getId()).getMarca().getDescricao();                
                //Incluir nova linha na Tabela
                
                model.addRow(saida);    
                
                
            }

        } catch (Exception ex) {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopo2 = new javax.swing.JPanel();
        jLabelEmpresa2 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jLabelIdentificador = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelRenavem = new javax.swing.JLabel();
        jLabelPrecoCompra = new javax.swing.JLabel();
        jTextFieldPrecoCompra = new javax.swing.JTextField();
        jLabelPrecoVenda = new javax.swing.JLabel();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jLabelAnoDeFabricacao = new javax.swing.JLabel();
        jLabelAnoDoModelo = new javax.swing.JLabel();
        jLabelCombustivel = new javax.swing.JLabel();
        jComboBoxCombustivel = new javax.swing.JComboBox<>();
        jLabelQuilometragem = new javax.swing.JLabel();
        jTextFieldQuilometragem = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel1Situacao = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jLabelBotaoIncluir2 = new javax.swing.JLabel();
        jLabelBotaoAlterar2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jFormattedTextFieldPlaca = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAnoFabricacao = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAnoModelo = new javax.swing.JFormattedTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel1Situacao1 = new javax.swing.JLabel();
        jComboBoxModelos = new javax.swing.JComboBox<>();
        jLabelPrecoCompra1 = new javax.swing.JLabel();
        jTextFieldRenavem = new javax.swing.JFormattedTextField();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelTopo2.setBackground(new java.awt.Color(0, 0, 51));

        jLabelEmpresa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/designed2.png"))); // NOI18N

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setText("Cadastro de veiculos");

        javax.swing.GroupLayout jPanelTopo2Layout = new javax.swing.GroupLayout(jPanelTopo2);
        jPanelTopo2.setLayout(jPanelTopo2Layout);
        jPanelTopo2Layout.setHorizontalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanelTopo2Layout.setVerticalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopo2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelTopo2);
        jPanelTopo2.setBounds(0, 0, 910, 130);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jTextFieldIdentificador.setEditable(false);
        jTextFieldIdentificador.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificadorActionPerformed(evt);
            }
        });

        jLabelIdentificador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelIdentificador.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdentificador.setText("Identificador");

        jLabelPlaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPlaca.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPlaca.setText("Placa");

        jLabelRenavem.setBackground(new java.awt.Color(0, 0, 0));
        jLabelRenavem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRenavem.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRenavem.setText("Renavam");

        jLabelPrecoCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecoCompra.setText("Preço Compra");

        jTextFieldPrecoCompra.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecoCompra.setForeground(new java.awt.Color(0, 0, 0));

        jLabelPrecoVenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecoVenda.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecoVenda.setText("Preço Venda");

        jTextFieldPrecoVenda.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecoVenda.setForeground(new java.awt.Color(0, 0, 0));

        jLabelAnoDeFabricacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAnoDeFabricacao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAnoDeFabricacao.setText("Ano De Fabricação");

        jLabelAnoDoModelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAnoDoModelo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAnoDoModelo.setText("Ano Do Modelo");

        jLabelCombustivel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCombustivel.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCombustivel.setText("Combustivel");

        jComboBoxCombustivel.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCombustivel.setForeground(new java.awt.Color(0, 0, 0));

        jLabelQuilometragem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelQuilometragem.setForeground(new java.awt.Color(0, 0, 0));
        jLabelQuilometragem.setText("Quilometragem");

        jTextFieldQuilometragem.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldQuilometragem.setForeground(new java.awt.Color(0, 0, 0));

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipo.setText("Tipo");

        jComboBoxTipo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1Situacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1Situacao.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1Situacao.setText("Situação");

        jComboBoxSituacao.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxSituacao.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoActionPerformed(evt);
            }
        });

        jLabelBotaoIncluir2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoIncluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botao incluir normal.png"))); // NOI18N
        jLabelBotaoIncluir2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoIncluir2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluir2MouseMoved(evt);
            }
        });
        jLabelBotaoIncluir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluir2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluir2MouseExited(evt);
            }
        });

        jLabelBotaoAlterar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoAlterar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botaoalterar.png"))); // NOI18N
        jLabelBotaoAlterar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoAlterar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterar2MouseMoved(evt);
            }
        });
        jLabelBotaoAlterar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterar2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterar2MouseExited(evt);
            }
        });

        jTableVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        jTableVeiculo.setForeground(new java.awt.Color(0, 0, 0));
        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Renavam", "Preço Compra", "Preço Venda", "Ano Fabricação", "Ano Modelo", "Combustivel", "Quilometragem", "Tipo", "Situação", "Categoria", "Modelo", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculo.setRowHeight(40);
        jTableVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVeiculo);

        jFormattedTextFieldPlaca.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldPlaca.setForeground(new java.awt.Color(0, 0, 0));
        try {
            jFormattedTextFieldPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jFormattedTextFieldAnoFabricacao.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldAnoFabricacao.setForeground(new java.awt.Color(0, 0, 0));
        try {
            jFormattedTextFieldAnoFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFormattedTextFieldAnoModelo.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldAnoModelo.setForeground(new java.awt.Color(0, 0, 0));
        try {
            jFormattedTextFieldAnoModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBoxCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCategoria.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1Situacao1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1Situacao1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1Situacao1.setText("Categoria");

        jComboBoxModelos.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxModelos.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModelosActionPerformed(evt);
            }
        });

        jLabelPrecoCompra1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecoCompra1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecoCompra1.setText("Modelo");

        try {
            jTextFieldRenavem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldQuilometragem, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelIdentificador)
                                        .addComponent(jTextFieldIdentificador)
                                        .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                    .addComponent(jLabelPrecoVenda)))
                            .addComponent(jLabelQuilometragem))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPlaca)
                            .addComponent(jLabelAnoDeFabricacao)
                            .addComponent(jComboBoxTipo, 0, 131, Short.MAX_VALUE)
                            .addComponent(jLabelTipo)
                            .addComponent(jFormattedTextFieldPlaca)
                            .addComponent(jFormattedTextFieldAnoFabricacao))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSituacao, 0, 148, Short.MAX_VALUE)
                            .addComponent(jLabelRenavem)
                            .addComponent(jLabelAnoDoModelo)
                            .addComponent(jLabel1Situacao)
                            .addComponent(jFormattedTextFieldAnoModelo)
                            .addComponent(jTextFieldRenavem))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCombustivel)
                                .addComponent(jLabelPrecoCompra)
                                .addComponent(jTextFieldPrecoCompra)
                                .addComponent(jComboBoxCombustivel, 0, 149, Short.MAX_VALUE)
                                .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1Situacao1))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxModelos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrecoCompra1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(495, 495, 495)
                                .addComponent(jLabelBotaoIncluir2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBotaoAlterar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentificador)
                    .addComponent(jLabelPlaca)
                    .addComponent(jLabelRenavem)
                    .addComponent(jLabelPrecoCompra)
                    .addComponent(jLabelPrecoCompra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRenavem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecoVenda)
                    .addComponent(jLabelAnoDeFabricacao)
                    .addComponent(jLabelAnoDoModelo)
                    .addComponent(jLabelCombustivel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuilometragem)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabel1Situacao)
                            .addComponent(jLabel1Situacao1)))
                    .addComponent(jLabelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBotaoIncluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBotaoAlterar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 130, 910, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificadorActionPerformed

    private void jLabelBotaoIncluir2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluir2MouseMoved

        jLabelBotaoIncluir2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluirencima.png");
        jLabelBotaoIncluir2.setIcon(iconeIncluirMouse);
    }//GEN-LAST:event_jLabelBotaoIncluir2MouseMoved

    private void jLabelBotaoIncluir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluir2MouseClicked
          try {
              if(jFormattedTextFieldAnoFabricacao.getText().equals("    ")||jFormattedTextFieldAnoModelo.getText().equals("    ")||jTextFieldPrecoCompra.getText().equals("")||jTextFieldPrecoVenda.getText().equals("")|| jTextFieldQuilometragem.getText().equals("")||jTextFieldRenavem.getText().equals("           ")||jComboBoxCategoria.getSelectedItem() == null){
           JOptionPane.showMessageDialog(this, "Campos Faltando");
             
           }else{
              
          int id = 0;
          int idModelo = 0;
          String tipoV = "";
          String situ = "";
          String combustivel = "";
          jComboBoxSituacao.setSelectedIndex(1);
              switch (jComboBoxCombustivel.getSelectedIndex()) {
                  case 0:
                      combustivel = Combustivel.GASOLINA + "";
                      break;
                  case 1:
                      combustivel = Combustivel.DIESEL + "";
                      break;
                  case 2:
                      combustivel = Combustivel.FLEX + "";
                      break;
                  case 3:
                      combustivel = Combustivel.ELETRICO + "";
                      break;
                  case 4:
                      combustivel = Combustivel.GNV + "";
                      break;
                  default:
                      break;
              }
          switch (jComboBoxTipo.getSelectedIndex()) {
                  case 0:
                      tipoV = VeiculoTipo.HATCH + "";
                      break;
                  case 1:
                        tipoV = VeiculoTipo.SEDAN +"";
                      break;
                  case 2:
                      tipoV = VeiculoTipo.SUV  +"";
                      break;
                  case 3:
                      tipoV = VeiculoTipo.PICKUP+ "";
                      break;
                      default:
                      break;
              }
              switch (jComboBoxSituacao.getSelectedIndex()) {
                  case 0:
                      situ = Situacao.LOCADO+"";
                      break;
                  case 1:
                        situ = Situacao.DISPONIVEL+"";
                      break;
                  case 2:
                      situ = Situacao.MANUTENCAO+"";
                      break;
                  case 3:
                      situ = Situacao.VENDIDO+"";
                      break;
                      default:
                      break;
              }
          
            
        Veiculo objeto = new Veiculo(0, jFormattedTextFieldPlaca.getText(), Long.parseLong(jTextFieldRenavem.getText()), Float.parseFloat(jTextFieldPrecoCompra.getText()), 
 Float.parseFloat(jTextFieldPrecoVenda.getText()), Integer.parseInt(jFormattedTextFieldAnoFabricacao.getText()), 
 Integer.parseInt(jFormattedTextFieldAnoModelo.getText()), Combustivel.valueOf(combustivel), Integer.parseInt(jTextFieldQuilometragem.getText()),VeiculoTipo.valueOf(tipoV),
  Situacao.valueOf(situ), categoria.buscar(id),modelo.buscar(idModelo));
        
        ArrayList<Categoria> lista = categoria.listagem();
          for(int i = 0; i < lista.size(); i++){
          if(jComboBoxCategoria.getSelectedItem().equals(lista.get(i).getDescricao())){
              objeto.setCategoria(lista.get(i));
          }
          }
           ArrayList<Modelo> listaModelos = modelo.listagemModelo();
          for(int i = 0; i < listaModelos.size(); i++){
          if(jComboBoxModelos.getSelectedItem().equals(listaModelos.get(i).getDescricao())){
              objeto.setModelo(listaModelos.get(i));
          }
          }
          
          objetoVeiculo.verificar(objeto);
          objetoVeiculo.incluir(objeto);
          imprimirDadosNaGrid(objetoVeiculo.listagemVeiculo());
          
    } }catch (Exception ex) {
            Logger.getLogger(CadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
         


        
    }//GEN-LAST:event_jLabelBotaoIncluir2MouseClicked

    private void jLabelBotaoIncluir2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluir2MouseExited
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluir.png");
        jLabelBotaoIncluir2.setIcon(iconeIncluirMouse);
    }//GEN-LAST:event_jLabelBotaoIncluir2MouseExited

    private void jLabelBotaoAlterar2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterar2MouseMoved
        jLabelBotaoAlterar2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterarencima.png");
        jLabelBotaoAlterar2.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterar2MouseMoved

    private void jLabelBotaoAlterar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterar2MouseClicked
       if(jTableVeiculo.getSelectedRow() != -1){
           if(jFormattedTextFieldAnoFabricacao.getText().equals("    ")||jFormattedTextFieldAnoModelo.getText().equals("    ")||jTextFieldPrecoCompra.getText().equals("")||jTextFieldPrecoVenda.getText().equals("")|| jTextFieldQuilometragem.getText().equals("")||jTextFieldRenavem.getText().equals("           ")){
           JOptionPane.showMessageDialog(this, "Campos Faltando");
           }else{
               
        try{ 
        int id = 0;
        int idModelo = 0;
          String tipoV = "";
          String situ = "";
          String combustivel = "";
          
              switch (jComboBoxCombustivel.getSelectedIndex()) {
                  case 0:
                      combustivel = Combustivel.GASOLINA + "";
                      break;
                  case 1:
                      combustivel = Combustivel.DIESEL + "";
                      break;
                  case 2:
                      combustivel = Combustivel.FLEX + "";
                      break;
                  case 3:
                      combustivel = Combustivel.ELETRICO + "";
                      break;
                  case 4:
                      combustivel = Combustivel.GNV + "";
                      break;
                  default:
                      break;
              }
          switch (jComboBoxTipo.getSelectedIndex()) {
                  case 0:
                      tipoV = VeiculoTipo.HATCH + "";
                      break;
                  case 1:
                        tipoV = VeiculoTipo.SEDAN +"";
                      break;
                  case 2:
                      tipoV = VeiculoTipo.SUV  +"";
                      break;
                  case 3:
                      tipoV = VeiculoTipo.PICKUP+ "";
                      break;
                      default:
                      break;
              }
              switch (jComboBoxSituacao.getSelectedIndex()) {
                  case 0:
                      situ = Situacao.LOCADO+"";
                      break;
                  case 1:
                        situ = Situacao.DISPONIVEL+"";
                      break;
                  case 2:
                      situ = Situacao.MANUTENCAO+"";
                      break;
                  case 3:
                      situ = Situacao.VENDIDO+"";
                      break;
                      default:
                      break;
              }
          
            
        Veiculo objeto = new Veiculo(Integer.parseInt(jTextFieldIdentificador.getText()), jFormattedTextFieldPlaca.getText(), Long.parseLong(jTextFieldRenavem.getText()), Float.parseFloat(jTextFieldPrecoCompra.getText()), 
 Float.parseFloat(jTextFieldPrecoVenda.getText()), Integer.parseInt(jFormattedTextFieldAnoFabricacao.getText()), 
 Integer.parseInt(jFormattedTextFieldAnoModelo.getText()), Combustivel.valueOf(combustivel), Integer.parseInt(jTextFieldQuilometragem.getText()),VeiculoTipo.valueOf(tipoV),
  Situacao.valueOf(situ), categoria.buscar(id),modelo.buscar(idModelo));
            ArrayList<Categoria> lista = categoria.listagem();
            for (int i = 0; i < lista.size(); i++) {
                if (jComboBoxCategoria.getSelectedItem().equals(lista.get(i).getDescricao())) {
                    objeto.setCategoria(lista.get(i));
                }
            }
           ArrayList<Modelo> listaModelos = modelo.listagemModelo();
          for(int i = 0; i < listaModelos.size(); i++){
          if(jComboBoxModelos.getSelectedItem().equals(listaModelos.get(i).getDescricao())){
              objeto.setModelo(listaModelos.get(i));
          }
         
          }
            objetoVeiculo.verificar(objeto);
           
             objetoVeiculo.alterar(objeto);
            imprimirDadosNaGrid(objetoVeiculo.listagemVeiculo());
            jComboBoxSituacao.setEnabled(false);
        
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
           
}
       }
       }else{
           JOptionPane.showMessageDialog(this, "Selecione o veículo para alterar");
       }
    }//GEN-LAST:event_jLabelBotaoAlterar2MouseClicked

    private void jLabelBotaoAlterar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterar2MouseExited
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterar.png");
        jLabelBotaoAlterar2.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterar2MouseExited

    private void jComboBoxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSituacaoActionPerformed

    private void jTableVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculoMouseClicked
        try {
             jComboBoxSituacao.setEnabled(true);
            jTextFieldIdentificador.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 0).toString());
            jFormattedTextFieldPlaca.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 1).toString());
            jTextFieldRenavem.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 2).toString());
            jTextFieldPrecoCompra.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 3).toString());
            jTextFieldPrecoVenda.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 4).toString());
            jFormattedTextFieldAnoFabricacao.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 5).toString());
            jFormattedTextFieldAnoModelo.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 6).toString());
            
            String combustivel = jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 7).toString();
            jComboBoxCombustivel.setSelectedItem(Combustivel.valueOf(combustivel));
            
            jTextFieldQuilometragem.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 8).toString());
            String tipoV = jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 9).toString();
            jComboBoxTipo.setSelectedItem(VeiculoTipo.valueOf(tipoV));
            String situ = jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 10).toString();
            jComboBoxSituacao.setSelectedItem(Situacao.valueOf(situ));
            String categoriaCombo = jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 11).toString();
            Categoria obj = new Categoria();
            Modelo modelo = new Modelo();
            obj.setDescricao(categoriaCombo);
            jComboBoxCategoria.setSelectedItem(obj.getDescricao());
            String modeloCombo = jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 12).toString();
            modelo.setDescricao(modeloCombo);
            jComboBoxModelos.setSelectedItem(modelo.getDescricao());
        } catch (Exception ex) {
            Logger.getLogger(CadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_jTableVeiculoMouseClicked

    private void jComboBoxModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModelosActionPerformed
        try {
            ArrayList<Modelo> listaModelos = modelo.listagemModelo();
            for(int i = 0; i < listaModelos.size(); i++){
                if(jComboBoxModelos.getSelectedItem().equals(listaModelos.get(i).getDescricao())){
                    String iconModelo = listaModelos.get(i).getUrl();
                    String iconMarca = listaModelos.get(i).getMarca().getUrl();
                    ImageIcon modelo = new ImageIcon(iconModelo);
                    ImageIcon marca = new ImageIcon(iconMarca);
                    modelo.setImage(modelo.getImage().getScaledInstance(jLabelModelo.getWidth(), jLabelModelo.getHeight(), 1));
                    marca.setImage(marca.getImage().getScaledInstance(jLabelMarca.getWidth(), jLabelMarca.getHeight(), 1));
                    jLabelModelo.setIcon(modelo);
                    jLabelMarca.setIcon(marca);
                }
            }
        }catch(Exception e){
                    
                    }
    }//GEN-LAST:event_jComboBoxModelosActionPerformed
    private void carregarComboBox(){
        jComboBoxCombustivel.setModel(new DefaultComboBoxModel<>(Combustivel.values()));
        jComboBoxSituacao.setModel(new DefaultComboBoxModel<>(Situacao.values()));
        jComboBoxTipo.setModel(new DefaultComboBoxModel<>(VeiculoTipo.values()));
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<com.tllr.enums.Combustivel> jComboBoxCombustivel;
    private javax.swing.JComboBox<String> jComboBoxModelos;
    private javax.swing.JComboBox<Situacao> jComboBoxSituacao;
    private javax.swing.JComboBox<VeiculoTipo> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldAnoFabricacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldAnoModelo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPlaca;
    private javax.swing.JLabel jLabel1Situacao;
    private javax.swing.JLabel jLabel1Situacao1;
    private javax.swing.JLabel jLabelAnoDeFabricacao;
    private javax.swing.JLabel jLabelAnoDoModelo;
    private javax.swing.JLabel jLabelBotaoAlterar2;
    private javax.swing.JLabel jLabelBotaoIncluir2;
    private javax.swing.JLabel jLabelCombustivel;
    private javax.swing.JLabel jLabelEmpresa2;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPrecoCompra;
    private javax.swing.JLabel jLabelPrecoCompra1;
    private javax.swing.JLabel jLabelPrecoVenda;
    private javax.swing.JLabel jLabelQuilometragem;
    private javax.swing.JLabel jLabelRenavem;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTopo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldPrecoCompra;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldQuilometragem;
    private javax.swing.JFormattedTextField jTextFieldRenavem;
    // End of variables declaration//GEN-END:variables
}
