/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tllr.visao;

import com.tllr.controle.ClienteControle;
import com.tllr.controle.IClienteControle;
import com.tllr.controle.IMotoristaControle;
import com.tllr.controle.MotoristaControle;
import com.tllr.enums.TipoCliente;
import com.tllr.modelos.Cliente;
import com.tllr.modelos.Motorista;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patricia
 */
public class TelaPlanilhaMotorista extends javax.swing.JFrame {
    IMotoristaControle motoristaControle = new MotoristaControle();
    String[] saida;
    AlteracaoDeMotorista chamar;
  
    public TelaPlanilhaMotorista() {
        initComponents();
       setLocationRelativeTo(null);
        try {
            imprimirDadosNaGrid(motoristaControle.listagemMotorista());
           
            } catch (Exception ex) {
            Logger.getLogger(TelaPlanilhaMotorista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
        
    public void imprimirDadosNaGrid(ArrayList<Motorista> listaDeMotoristas){
         
            DefaultTableModel model = (DefaultTableModel) jTableClientes.getModel();
            //Limpa a tabela 
            model.setNumRows(0);
            Iterator<Motorista> lista = listaDeMotoristas.iterator();               

            while (lista.hasNext()) {
             // return id + ";" + nome + ";" + numeroCnh + ";" + dataValidade + ";" + endereco + ";" + telefone + ";" + cliente.getId() ;
                saida = new String[8];
                Motorista aux = lista.next();
                saida[0] = aux.getId() + "";
                saida[1] = aux.getNome();
                saida[2] = aux.getNumeroCnh() + "";
                saida[3] = aux.getDataValidade()+ "";
                saida[4] = aux.getEndereco().getCEP() +";"+ aux.getEndereco().getBairro() +";"+  aux.getEndereco().getCidade() 
                        +";"+ aux.getEndereco().getComplemento() +";"+ aux.getEndereco().getEstado() +";"+ aux.getEndereco().getLogradouro();
                saida[5] = "+"+aux.getTelefone().getDDI() + "("+aux.getTelefone().getDDD() +")" + aux.getTelefone().getNumero()+"";
               saida[6] = aux.getCliente().getCpf_cnpj();
               
                //Incluir nova linha na Tabela
                model.addRow(saida);
                
            }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo2 = new javax.swing.JPanel();
        jPanelTopo2 = new javax.swing.JPanel();
        jLabelEmpresa2 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFundo2.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFundo2.setLayout(null);

        jPanelTopo2.setBackground(new java.awt.Color(0, 0, 51));

        jLabelEmpresa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/designed2.png"))); // NOI18N

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setText("Escolha o Cliente");

        javax.swing.GroupLayout jPanelTopo2Layout = new javax.swing.GroupLayout(jPanelTopo2);
        jPanelTopo2.setLayout(jPanelTopo2Layout);
        jPanelTopo2Layout.setHorizontalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanelTopo2Layout.setVerticalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopo2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelFundo2.add(jPanelTopo2);
        jPanelTopo2.setBounds(0, 0, 1180, 130);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CNH", "Data Validade", "Endereco", "Telefone", "CPF/CNPJ -Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setRowHeight(55);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableClientes.getColumnModel().getColumn(0).setMaxWidth(25);
            jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableClientes.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableClientes.getColumnModel().getColumn(2).setMinWidth(120);
            jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableClientes.getColumnModel().getColumn(2).setMaxWidth(150);
            jTableClientes.getColumnModel().getColumn(3).setMinWidth(120);
            jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTableClientes.getColumnModel().getColumn(3).setMaxWidth(150);
            jTableClientes.getColumnModel().getColumn(4).setMinWidth(350);
            jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(370);
            jTableClientes.getColumnModel().getColumn(4).setMaxWidth(400);
            jTableClientes.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTableClientes.getColumnModel().getColumn(5).setMaxWidth(200);
            jTableClientes.getColumnModel().getColumn(6).setMinWidth(120);
            jTableClientes.getColumnModel().getColumn(6).setPreferredWidth(150);
            jTableClientes.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        jPanelFundo2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 420, 1180, 210);

        jButton3.setBackground(new java.awt.Color(21, 21, 88));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/casa (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelFundo2.add(jButton3);
        jButton3.setBounds(10, 140, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/botaoalterar.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanelFundo2.add(jLabel1);
        jLabel1.setBounds(20, 380, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelFundo2, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(jTableClientes.getSelectedRow() != -1){
        chamar = new AlteracaoDeMotorista();
        
        
        String[] itensTable = new String[7];
        itensTable[0] = jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0).toString();
        itensTable[1]= jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 1).toString();
        itensTable[2]= jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 2).toString();
        itensTable[3]= jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 3).toString();
        itensTable[4]= jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 4).toString();
        itensTable[5]= jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 5).toString();
        itensTable[6]= jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 6).toString();
        
        String telefone = jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 5).toString();
        String[] separar = telefone.split("");
        String numero = separar[7] + separar[8] +separar[9] + separar[10] + separar[11] + separar[12] + separar[13] + separar[14] + separar[15];
        chamar.receber(itensTable[0], itensTable[1], separar[1] + separar[2], separar[4] + separar[5], numero, itensTable[2], itensTable[3], itensTable[4]);
        chamar.setVisible(true);
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum motorista selecionado");
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPlanilhaMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEmpresa2;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelFundo2;
    private javax.swing.JPanel jPanelTopo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables
}
