/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tllr.visao;

import com.tllr.controle.AcessorioControle;
import com.tllr.controle.CategoriaControle;
import com.tllr.controle.ClienteControle;
import com.tllr.controle.IAcessorioControle;
import com.tllr.controle.ICategoriaControle;
import com.tllr.controle.IClienteControle;
import com.tllr.controle.ILocacaoControle;
import com.tllr.controle.IModeloControle;
import com.tllr.controle.IMotoristaControle;
import com.tllr.controle.IVeiculoControle;
import com.tllr.controle.LocacaoControle;
import com.tllr.controle.ModeloControle;
import com.tllr.controle.MotoristaControle;
import com.tllr.controle.VeiculoControle;
import com.tllr.enums.Combustivel;
import com.tllr.enums.Situacao;
import com.tllr.enums.SituacaoLocacao;
import com.tllr.enums.TipoCliente;
import com.tllr.enums.VeiculoTipo;
import com.tllr.modelos.Acessorio;
import com.tllr.modelos.Cliente;
import com.tllr.modelos.Locacao;
import com.tllr.modelos.Modelo;
import com.tllr.modelos.Motorista;
import com.tllr.modelos.Veiculo;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patricia
 */
public class TelaPlanilhaLocacao extends javax.swing.JFrame {
ILocacaoControle locacaoControle = new LocacaoControle();
    /**
     * Creates new form TelaPlanilhaLocacao
     */
    public TelaPlanilhaLocacao() {
        initComponents();
    try {
        setLocationRelativeTo(null);
        imprimirDadosNaGrid(locacaoControle.listagemLocacao());
    } catch (Exception ex) {
        Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
     public void imprimirDadosNaGrid(ArrayList<Locacao> listaDeVeiculos) {
        DefaultTableModel model = (DefaultTableModel) jTableLocacao.getModel();
        model.setNumRows(0);
        Iterator<Locacao> lista = listaDeVeiculos.iterator();
        try {
            while (lista.hasNext()) {
                String[] saida = new String[10];
                Locacao aux = lista.next();
                saida[0] = "" + aux.getId();
                saida[1] = aux.getDiaInicio() + "/" + aux.getMesInicio()+"/"+aux.getAnoInicio();
                saida[2] = aux.getDiaFinal() + "/" + aux.getMesFinal() + "/" + aux.getAnoFinal();
                saida[3] = aux.getVeiculo().getPlaca();
                saida[4] = aux.getVeiculo().getModelo().getDescricao();
                saida[5] = aux.getValorCalcao()+"";
                saida[6] = aux.getSituacaoLocacao()+"";
                saida[7] = aux.getMotorista().getNome()+"";
                saida[8] = aux.getMotorista().getNumeroCnh()+"";
                saida[9] = aux.getCliente().getCpf_cnpj() + "";
                //Incluir nova linha na Tabela
                model.addRow(saida);        
                
            }
        }catch(Exception e){
                            Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(Level.SEVERE, null, e);

                    }
        }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo2 = new javax.swing.JPanel();
        jPanelTopo2 = new javax.swing.JPanel();
        jLabelEmpresa2 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLocacao = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonDevolver = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFundo2.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFundo2.setLayout(null);

        jPanelTopo2.setBackground(new java.awt.Color(0, 0, 51));

        jLabelEmpresa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/designed2.png"))); // NOI18N

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setText("Cadastro de modelos");

        javax.swing.GroupLayout jPanelTopo2Layout = new javax.swing.GroupLayout(jPanelTopo2);
        jPanelTopo2.setLayout(jPanelTopo2Layout);
        jPanelTopo2Layout.setHorizontalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanelTopo2Layout.setVerticalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopo2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelFundo2.add(jPanelTopo2);
        jPanelTopo2.setBounds(0, 0, 1180, 130);

        jTableLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data Inicio", "Data Final", "Placa Veiculo", "Modelo Veiculo", "Valor", "Status Locacao", "Nome Motorista", "Numero CNH", "CPF/CNPJ - Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLocacao.setRowHeight(55);
        jTableLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLocacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLocacao);
        if (jTableLocacao.getColumnModel().getColumnCount() > 0) {
            jTableLocacao.getColumnModel().getColumn(0).setMinWidth(25);
            jTableLocacao.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableLocacao.getColumnModel().getColumn(0).setMaxWidth(25);
            jTableLocacao.getColumnModel().getColumn(1).setMinWidth(75);
            jTableLocacao.getColumnModel().getColumn(1).setPreferredWidth(75);
            jTableLocacao.getColumnModel().getColumn(1).setMaxWidth(75);
            jTableLocacao.getColumnModel().getColumn(2).setMinWidth(75);
            jTableLocacao.getColumnModel().getColumn(2).setPreferredWidth(75);
            jTableLocacao.getColumnModel().getColumn(2).setMaxWidth(75);
            jTableLocacao.getColumnModel().getColumn(3).setMinWidth(75);
            jTableLocacao.getColumnModel().getColumn(3).setPreferredWidth(75);
            jTableLocacao.getColumnModel().getColumn(3).setMaxWidth(75);
            jTableLocacao.getColumnModel().getColumn(4).setMinWidth(75);
            jTableLocacao.getColumnModel().getColumn(4).setPreferredWidth(75);
            jTableLocacao.getColumnModel().getColumn(4).setMaxWidth(75);
            jTableLocacao.getColumnModel().getColumn(5).setMinWidth(75);
            jTableLocacao.getColumnModel().getColumn(5).setPreferredWidth(75);
            jTableLocacao.getColumnModel().getColumn(5).setMaxWidth(75);
            jTableLocacao.getColumnModel().getColumn(6).setMinWidth(100);
            jTableLocacao.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableLocacao.getColumnModel().getColumn(6).setMaxWidth(100);
            jTableLocacao.getColumnModel().getColumn(7).setMinWidth(100);
            jTableLocacao.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableLocacao.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jPanelFundo2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 430, 910, 210);

        jButton2.setBackground(new java.awt.Color(21, 21, 88));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/curva-de-seta-apontando-para-a-esquerda.png"))); // NOI18N
        jButton2.setText("Marcas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelFundo2.add(jButton2);
        jButton2.setBounds(10, 140, 90, 30);

        jButton3.setBackground(new java.awt.Color(21, 21, 88));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/casa (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelFundo2.add(jButton3);
        jButton3.setBounds(110, 140, 30, 30);

        jLabel1.setText("Filtrar por status da locação");
        jPanelFundo2.add(jLabel1);
        jLabel1.setBounds(660, 330, 150, 16);

        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });
        jPanelFundo2.add(jButtonDevolver);
        jButtonDevolver.setBounds(10, 390, 76, 22);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelFundo2.add(jButtonCancelar);
        jButtonCancelar.setBounds(110, 390, 90, 22);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanelFundo2.add(jTextField1);
        jTextField1.setBounds(660, 360, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelFundo2, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLocacaoMouseClicked

    }//GEN-LAST:event_jTableLocacaoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
    if(jTableLocacao.getSelectedRow() != -1){
        try {
        int idLocacao = Integer.parseInt(jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 0).toString());
        int idVeiculo = 0;
        int idMotorista = 0;
        int idCliente = 0;
        int idAcessorio = 0;
        IVeiculoControle veiculoControle = new VeiculoControle();
        IMotoristaControle motoristaControle = new MotoristaControle();
        IClienteControle clienteControle = new ClienteControle();
        IAcessorioControle acessorioControle = new AcessorioControle();
        ArrayList<Locacao> lista = locacaoControle.listagemLocacao();
        for(int i = 0; i < lista.size();i++){
            if(idLocacao == lista.get(i).getId()){
                idVeiculo = lista.get(i).getVeiculo().getId();
                idMotorista = lista.get(i).getMotorista().getId();
                idCliente = lista.get(i).getCliente().getId();
                idAcessorio = lista.get(i).getAcessorio().getId();
            }
        }
//aux.getDiaInicio() + "/" + aux.getMesInicio()+"/"+aux.getAnoInicio();
//                saida[2] = aux.getDiaFinal() + "/" + aux.getMesFinal() + "/" + aux.getAnoFinal();
String dataInicio = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 1).toString();
String[] repartirDataInicio = dataInicio.split("/");
String dataFinal = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 2).toString();
String[] repartirDataFinal = dataFinal.split("/");
Float valorTotal = Float.parseFloat(jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 5).toString());
        //    public Locacao(int id,int anoInicio, int mesInicio, int diaInicio, int anoFinal, int mesFinal, int diaFinal, float valorCalcao ,SituacaoLocacao situacaoLocacao, Cliente cliente, Veiculo veiculo, Acessorio acessorio,Motorista motorista) 

        Veiculo objetoVeiculo = new Veiculo(idVeiculo, veiculoControle.buscar(idVeiculo).getPlaca(),veiculoControle.buscar(idVeiculo).getRenavam() , veiculoControle.buscar(idVeiculo).getPrecoCompra(), veiculoControle.buscar(idVeiculo).getPrecoVenda(), veiculoControle.buscar(idVeiculo).getAnoDeFabricacao(), veiculoControle.buscar(idVeiculo).getAnoModelo(), veiculoControle.buscar(idVeiculo).getCombustivel(), veiculoControle.buscar(idVeiculo).getQuilometragem(), veiculoControle.buscar(idVeiculo).getTipoVeiculo(), Situacao.DISPONIVEL, veiculoControle.buscar(idVeiculo).getCategoria(), veiculoControle.buscar(idVeiculo).getModelo());
        Motorista objetoMotorista = new Motorista(idMotorista, motoristaControle.buscar(idMotorista).getNome(), motoristaControle.buscar(idMotorista).getNumeroCnh(), motoristaControle.buscar(idMotorista).getDataValidade(), motoristaControle.buscar(idMotorista).getEndereco(),motoristaControle.buscar(idMotorista).getTelefone(),motoristaControle.buscar(idMotorista).getCliente());
        Cliente objetoCliente = new Cliente(idCliente, clienteControle.buscar(idCliente).getCpf_cnpj(), clienteControle.buscar(idCliente).getNome(), clienteControle.buscar(idCliente).getRazaoSocial(), clienteControle.buscar(idCliente).getIdentidade(), clienteControle.buscar(idCliente).getTelefone(), clienteControle.buscar(idCliente).getEmail(), clienteControle.buscar(idCliente).getEndereco(), clienteControle.buscar(idCliente).getTipoCliente());
        Acessorio objetoAcessorio = new Acessorio(idAcessorio,acessorioControle.buscar(idAcessorio).getDescricao() ,acessorioControle.buscar(idAcessorio).getValorLocacao());
        Locacao objetoLocacao = new Locacao(idLocacao, Integer.parseInt(repartirDataInicio[2]),Integer.parseInt(repartirDataInicio[1]) ,Integer.parseInt(repartirDataInicio[0]), Integer.parseInt(repartirDataFinal[2]),Integer.parseInt(repartirDataFinal[1]) ,Integer.parseInt(repartirDataFinal[0]), valorTotal, SituacaoLocacao.FINALIZADA, objetoCliente, objetoVeiculo, objetoAcessorio, objetoMotorista);
         String verificar = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 6).toString();
        if( verificar.equals(SituacaoLocacao.EM_ABERTO.toString())){
        locacaoControle.devolver(objetoLocacao);
        veiculoControle.alterar(objetoVeiculo);
        imprimirDadosNaGrid(locacaoControle.listagemLocacao());
         }else{
            JOptionPane.showMessageDialog(this, "Só é possivel devolver veículos locados");
        }
    } catch (Exception ex) {
        Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(Level.SEVERE, null, ex);
    }
        }else{
                JOptionPane.showMessageDialog(this, "Selecione algum item para devolver");
                }
    
       
    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        if(jTableLocacao.getSelectedRow() != -1){
        try {
        int idLocacao = Integer.parseInt(jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 0).toString());
        int idVeiculo = 0;
        int idMotorista = 0;
        int idCliente = 0;
        int idAcessorio = 0;
        IVeiculoControle veiculoControle = new VeiculoControle();
        IMotoristaControle motoristaControle = new MotoristaControle();
        IClienteControle clienteControle = new ClienteControle();
        IAcessorioControle acessorioControle = new AcessorioControle();
        ArrayList<Locacao> lista = locacaoControle.listagemLocacao();
        for(int i = 0; i < lista.size();i++){
            if(idLocacao == lista.get(i).getId()){
                idVeiculo = lista.get(i).getVeiculo().getId();
                idMotorista = lista.get(i).getMotorista().getId();
                idCliente = lista.get(i).getCliente().getId();
                idAcessorio = lista.get(i).getAcessorio().getId();
            }
        }
//aux.getDiaInicio() + "/" + aux.getMesInicio()+"/"+aux.getAnoInicio();
//                saida[2] = aux.getDiaFinal() + "/" + aux.getMesFinal() + "/" + aux.getAnoFinal();
String dataInicio = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 1).toString();
String[] repartirDataInicio = dataInicio.split("/");
String dataFinal = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 2).toString();
String[] repartirDataFinal = dataFinal.split("/");
Float valorTotal = Float.parseFloat(jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 5).toString());
        //    public Locacao(int id,int anoInicio, int mesInicio, int diaInicio, int anoFinal, int mesFinal, int diaFinal, float valorCalcao ,SituacaoLocacao situacaoLocacao, Cliente cliente, Veiculo veiculo, Acessorio acessorio,Motorista motorista) 

        Veiculo objetoVeiculo = new Veiculo(idVeiculo, veiculoControle.buscar(idVeiculo).getPlaca(),veiculoControle.buscar(idVeiculo).getRenavam() , veiculoControle.buscar(idVeiculo).getPrecoCompra(), veiculoControle.buscar(idVeiculo).getPrecoVenda(), veiculoControle.buscar(idVeiculo).getAnoDeFabricacao(), veiculoControle.buscar(idVeiculo).getAnoModelo(), veiculoControle.buscar(idVeiculo).getCombustivel(), veiculoControle.buscar(idVeiculo).getQuilometragem(), veiculoControle.buscar(idVeiculo).getTipoVeiculo(), Situacao.DISPONIVEL, veiculoControle.buscar(idVeiculo).getCategoria(), veiculoControle.buscar(idVeiculo).getModelo());
        Motorista objetoMotorista = new Motorista(idMotorista, motoristaControle.buscar(idMotorista).getNome(), motoristaControle.buscar(idMotorista).getNumeroCnh(), motoristaControle.buscar(idMotorista).getDataValidade(), motoristaControle.buscar(idMotorista).getEndereco(),motoristaControle.buscar(idMotorista).getTelefone(),motoristaControle.buscar(idMotorista).getCliente());
        Cliente objetoCliente = new Cliente(idCliente, clienteControle.buscar(idCliente).getCpf_cnpj(), clienteControle.buscar(idCliente).getNome(), clienteControle.buscar(idCliente).getRazaoSocial(), clienteControle.buscar(idCliente).getIdentidade(), clienteControle.buscar(idCliente).getTelefone(), clienteControle.buscar(idCliente).getEmail(), clienteControle.buscar(idCliente).getEndereco(), clienteControle.buscar(idCliente).getTipoCliente());
        Acessorio objetoAcessorio = new Acessorio(idAcessorio,acessorioControle.buscar(idAcessorio).getDescricao() ,acessorioControle.buscar(idAcessorio).getValorLocacao());
        Locacao objetoLocacao = new Locacao(idLocacao, Integer.parseInt(repartirDataInicio[2]),Integer.parseInt(repartirDataInicio[1]) ,Integer.parseInt(repartirDataInicio[0]), Integer.parseInt(repartirDataFinal[2]),Integer.parseInt(repartirDataFinal[1]) ,Integer.parseInt(repartirDataFinal[0]), valorTotal, SituacaoLocacao.CANCELADA, objetoCliente, objetoVeiculo, objetoAcessorio, objetoMotorista);
        
        String verificar = jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(), 6).toString();
        if(verificar.equals(SituacaoLocacao.EM_ABERTO.toString())){        
        locacaoControle.cancelar(objetoLocacao);
        veiculoControle.alterar(objetoVeiculo);
        imprimirDadosNaGrid(locacaoControle.listagemLocacao());
            }else{
            JOptionPane.showMessageDialog(this, "Só é possivel cancelar veículos locados");
        }
        
    } catch (Exception ex) {
        Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(Level.SEVERE, null, ex);
    }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione algum item para cancelar");
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        
    }//GEN-LAST:event_jTextField1KeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPlanilhaLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEmpresa2;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelFundo2;
    private javax.swing.JPanel jPanelTopo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLocacao;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
