/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tllr.visao;

import com.tllr.controle.ClienteControle;
import com.tllr.controle.IClienteControle;
import com.tllr.enums.TipoCliente;
import com.tllr.modelos.Cliente;
import com.tllr.persistencia.IClienteDao;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patricia
 */
public class TelaPlanilhaClientes extends javax.swing.JFrame {
    IClienteControle clienteControle = new ClienteControle();
    TelaAlterarCliente cliente;
    String[] saida;
    /**
     * Creates new form TelaPlanilhaClientes
     */
    public TelaPlanilhaClientes() {
        initComponents();
       
        try {
            imprimirDadosNaGrid(clienteControle.listagemCliente());
                       setLocationRelativeTo(null);
            } catch (Exception ex) {
            Logger.getLogger(TelaPlanilhaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    public void imprimirDadosNaGrid(ArrayList<Cliente> listaDeClientes){
         
            DefaultTableModel model = (DefaultTableModel) jTableClientes.getModel();
            //Limpa a tabela 
            model.setNumRows(0);
            Iterator<Cliente> lista = listaDeClientes.iterator();               

            while (lista.hasNext()) {
             
                saida = new String[16];
                Cliente aux = lista.next();
                saida[0] = aux.getId() + "";
                saida[1] = aux.getCpf_cnpj();
                saida[2] = aux.getNome();
                saida[3] = aux.getRazaoSocial();
                saida[4] = aux.getIdentidade()+ "";
                saida[5] = "+"+aux.getTelefone().getDDI() + "("+aux.getTelefone().getDDD() +")" + aux.getTelefone().getNumero()+"";
                saida[6] = aux.getEmail();
                saida[7] = aux.getEndereco().getCEP() +";"+ aux.getEndereco().getBairro() +";"+  aux.getEndereco().getCidade() 
                        +";"+ aux.getEndereco().getComplemento() +";"+ aux.getEndereco().getEstado() +";"+ aux.getEndereco().getLogradouro();
                saida[8] = aux.getTipoCliente().toString();
                int i = 0;
               
                //Incluir nova linha na Tabela
                model.addRow(saida);
                
            }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo2 = new javax.swing.JPanel();
        jLabelBotaoAlterar2 = new javax.swing.JLabel();
        jPanelTopo2 = new javax.swing.JPanel();
        jLabelEmpresa2 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFundo2.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFundo2.setLayout(null);

        jLabelBotaoAlterar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoAlterar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botaoalterar.png"))); // NOI18N
        jLabelBotaoAlterar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoAlterar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterar2MouseMoved(evt);
            }
        });
        jLabelBotaoAlterar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterar2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterar2MouseExited(evt);
            }
        });
        jPanelFundo2.add(jLabelBotaoAlterar2);
        jLabelBotaoAlterar2.setBounds(20, 370, 90, 40);

        jPanelTopo2.setBackground(new java.awt.Color(0, 0, 51));

        jLabelEmpresa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/designed2.png"))); // NOI18N

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setText("Cadastro de modelos");

        javax.swing.GroupLayout jPanelTopo2Layout = new javax.swing.GroupLayout(jPanelTopo2);
        jPanelTopo2.setLayout(jPanelTopo2Layout);
        jPanelTopo2Layout.setHorizontalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanelTopo2Layout.setVerticalGroup(
            jPanelTopo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopo2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopo2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelFundo2.add(jPanelTopo2);
        jPanelTopo2.setBounds(0, 0, 1180, 130);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF/CNPJ", "Nome", "Razao Social", "Identidade", "Telefone", "Email", "Endereco", "Tipo de Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setRowHeight(55);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableClientes.getColumnModel().getColumn(0).setMaxWidth(25);
            jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableClientes.getColumnModel().getColumn(1).setMaxWidth(150);
            jTableClientes.getColumnModel().getColumn(2).setMinWidth(100);
            jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableClientes.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(85);
            jTableClientes.getColumnModel().getColumn(3).setMaxWidth(85);
            jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(85);
            jTableClientes.getColumnModel().getColumn(4).setMaxWidth(85);
            jTableClientes.getColumnModel().getColumn(5).setPreferredWidth(120);
            jTableClientes.getColumnModel().getColumn(5).setMaxWidth(120);
            jTableClientes.getColumnModel().getColumn(6).setPreferredWidth(200);
            jTableClientes.getColumnModel().getColumn(6).setMaxWidth(200);
            jTableClientes.getColumnModel().getColumn(8).setPreferredWidth(80);
            jTableClientes.getColumnModel().getColumn(8).setMaxWidth(80);
        }

        jPanelFundo2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 420, 1180, 210);

        jButton2.setBackground(new java.awt.Color(21, 21, 88));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/curva-de-seta-apontando-para-a-esquerda.png"))); // NOI18N
        jButton2.setText("Marcas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelFundo2.add(jButton2);
        jButton2.setBounds(10, 140, 90, 30);

        jButton3.setBackground(new java.awt.Color(21, 21, 88));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ImageAnimacoes/casa (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelFundo2.add(jButton3);
        jButton3.setBounds(110, 140, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelFundo2, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadastroMarcas chamar = new CadastroMarcas();
        this.dispose();
        chamar.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabelBotaoAlterar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterar2MouseExited

    }//GEN-LAST:event_jLabelBotaoAlterar2MouseExited

    private void jLabelBotaoAlterar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterar2MouseClicked
        if(jTableClientes.getSelectedRow() != - 1){
            this.dispose();

            cliente = new TelaAlterarCliente();
            String[] itensTable = new String[9];

            itensTable[0] = jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0).toString();
            itensTable[1]= jTableClientes.getValueAt(jTableClientes.getSelectedRow(),1).toString();
            itensTable[2] = jTableClientes.getValueAt(jTableClientes.getSelectedRow(),2).toString();
            itensTable[3] = jTableClientes.getValueAt(jTableClientes.getSelectedRow(),3).toString();
            itensTable[4] =  jTableClientes.getValueAt(jTableClientes.getSelectedRow(),4).toString();

            itensTable[5]  = jTableClientes.getValueAt(jTableClientes.getSelectedRow(),5).toString();
            String[] dividir = itensTable[5].split("");
            String telefone = dividir[7] + dividir[8] + dividir[9] + dividir[10] + dividir[11] + dividir[12] + dividir[13] + dividir[14] + dividir[15];

            itensTable[6] =  jTableClientes.getValueAt(jTableClientes.getSelectedRow(),6).toString();
            itensTable[7] =  jTableClientes.getValueAt(jTableClientes.getSelectedRow(),8).toString();

            itensTable[8] =  jTableClientes.getValueAt(jTableClientes.getSelectedRow(),7).toString();
            String[] endereco = itensTable[8].split(";");

            cliente.receber(itensTable[0],itensTable[1], itensTable[2], itensTable[3], itensTable[4], dividir[1] + dividir[2] , dividir[4] + dividir[5], telefone,itensTable[6], TipoCliente.valueOf(itensTable[7]));
            cliente.manterEndereco(endereco[0],endereco[1],endereco[2],endereco[3],endereco[4],endereco[5]);
            cliente.receberEpor();
            cliente.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Nenhum cliente sendo alterado, clique em algum na tabela para prosseguir");
        }
    }//GEN-LAST:event_jLabelBotaoAlterar2MouseClicked

    private void jLabelBotaoAlterar2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterar2MouseMoved

    }//GEN-LAST:event_jLabelBotaoAlterar2MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPlanilhaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPlanilhaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelBotaoAlterar2;
    private javax.swing.JLabel jLabelEmpresa2;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelFundo2;
    private javax.swing.JPanel jPanelTopo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables
}
