/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.tllr.visao;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import com.tllr.controle.IMarcaControle;
import com.tllr.controle.IModeloControle;
import com.tllr.controle.MarcaControle;
import com.tllr.controle.ModeloControle;
import com.tllr.imagensnatabela.JTableRenderer;
import com.tllr.modelos.Marca;
import com.tllr.modelos.Modelo;
import com.tllr.persistencia.IMarcaDao;
import com.tllr.persistencia.MarcaDao;
import com.tllr.persistencia.ModelosDao;
import java.awt.Canvas;
import java.awt.Cursor;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.vm.ci.meta.JavaKind.Int;
import com.tllr.persistencia.IModelosDao;

/**
 *
 * @author Usuario
 */
public class TelaDeCadastroModelo extends javax.swing.JInternalFrame {
     IModeloControle modeloControle = new ModeloControle();
                 IMarcaControle objetoMarca = new MarcaControle();

String urlMarca;
int idListagem =0; 

     /**
     * Creates new form TelaDeCadastroModelo
     */
    public TelaDeCadastroModelo() {
        initComponents();
        IMarcaControle objeto = new MarcaControle();
        
        try {
             ArrayList<Marca> lista = objeto.listagem();
             int tamanho = lista.size();
             String[] relacaoMarcas= new String[tamanho];
             for(int i = 0;i < lista.size(); i++){
                 relacaoMarcas[i] = lista.get(i).getDescricao();
                 jComboBoxMarca.addItem(relacaoMarcas[i]);
             }
            } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Marca não existe");
         }
        
        setBounds(0,0,943,650);
         jTextFieldIdentificador.setEnabled(false);
        jTextFieldUrl.setEnabled(false);
        try {
            
            imprimirDadosNaGrid(modeloControle.listagemModelo());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        
        
    }
 public void imprimirDadosNaGrid(ArrayList<Modelo>  listaDeModelos) {
            DefaultTableModel model = (DefaultTableModel) jTableModelos.getModel();
            JTableRenderer JtableRenderer = new JTableRenderer();
            jTableModelos.getColumnModel().getColumn(3).setCellRenderer(JtableRenderer);
            jTableModelos.getColumnModel().getColumn(4).setCellRenderer(JtableRenderer);
            
            Collections.sort(listaDeModelos);
            model.setNumRows(0);
            Iterator<Modelo> lista = listaDeModelos.iterator();               
            
            while (lista.hasNext()) {
                try {
                    String[] saida = new String[4];
                    Modelo aux = lista.next();
                    saida[0] = "" + aux.getId();
                    saida[1] = aux.getDescricao();
                    saida[2] = aux.getUrl();
                    saida [3] = objetoMarca.buscar(aux.getMarca().getId()).getUrl();
                   
                    ImageIcon iconlogo = new ImageIcon(aux.getUrl());
                    

                    
                    //Incluir nova linha na Tabela
                    Object[] dados = {saida[0], saida[1], saida[2],saida[3],iconlogo};
                    model.addRow(dados);
                    
                } catch (Exception ex) {
                    Logger.getLogger(TelaDeCadastroModelo.class.getName()).log(Level.SEVERE, null, ex);
                }
        
            }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMarca = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jPanelFundo = new javax.swing.JPanel();
        jLabelBotaoBuscar = new javax.swing.JLabel();
        jLabelBotaoAlterar = new javax.swing.JLabel();
        jLabelBotaoIncluir = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelModeloVeiculo2 = new javax.swing.JLabel();
        jPanelTopo = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelBorda = new javax.swing.JLabel();
        jLabelMarcaLogo = new javax.swing.JLabel();
        jLabelBorda1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModelos = new javax.swing.JTable();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jLabelIdentificador = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jLabelUrl = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(null);

        jLabelMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMarca.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMarca.setText("Marca");
        getContentPane().add(jLabelMarca);
        jLabelMarca.setBounds(20, 310, 42, 20);

        jComboBoxMarca.setBackground(new java.awt.Color(102, 102, 102));
        jComboBoxMarca.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMarcaMouseClicked(evt);
            }
        });
        jComboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMarca);
        jComboBoxMarca.setBounds(20, 340, 160, 22);

        jPanelFundo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFundo.setLayout(null);

        jLabelBotaoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botao buscar normal.png"))); // NOI18N
        jLabelBotaoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseMoved(evt);
            }
        });
        jLabelBotaoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseExited(evt);
            }
        });
        jPanelFundo.add(jLabelBotaoBuscar);
        jLabelBotaoBuscar.setBounds(530, 360, 93, 43);

        jLabelBotaoAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botaoalterar.png"))); // NOI18N
        jLabelBotaoAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoAlterar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseMoved(evt);
            }
        });
        jLabelBotaoAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseExited(evt);
            }
        });
        jPanelFundo.add(jLabelBotaoAlterar);
        jLabelBotaoAlterar.setBounds(120, 270, 90, 40);

        jLabelBotaoIncluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botao incluir normal.png"))); // NOI18N
        jLabelBotaoIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoIncluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseMoved(evt);
            }
        });
        jLabelBotaoIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseExited(evt);
            }
        });
        jPanelFundo.add(jLabelBotaoIncluir);
        jLabelBotaoIncluir.setBounds(10, 270, 90, 40);

        jLabelLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLogo.setText("Logo");
        jPanelFundo.add(jLabelLogo);
        jLabelLogo.setBounds(820, 160, 60, 32);

        jLabelModeloVeiculo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelModeloVeiculo2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelModeloVeiculo2.setText("Modelo Veículo");
        jPanelFundo.add(jLabelModeloVeiculo2);
        jLabelModeloVeiculo2.setBounds(560, 160, 180, 32);

        jPanelTopo.setBackground(new java.awt.Color(0, 0, 51));

        jLabelEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/designed2.png"))); // NOI18N

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastro de modelos");

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelFundo.add(jPanelTopo);
        jPanelTopo.setBounds(0, 0, 930, 130);

        jLabelModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelFundo.add(jLabelModelo);
        jLabelModelo.setBounds(610, 220, 70, 70);

        jLabelBorda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/borda.png"))); // NOI18N
        jPanelFundo.add(jLabelBorda);
        jLabelBorda.setBounds(600, 210, 90, 90);

        jLabelMarcaLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelFundo.add(jLabelMarcaLogo);
        jLabelMarcaLogo.setBounds(820, 220, 70, 70);

        jLabelBorda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/borda.png"))); // NOI18N
        jPanelFundo.add(jLabelBorda1);
        jLabelBorda1.setBounds(810, 210, 90, 90);

        jTableModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelos", "URL", "Foto", "Logo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableModelos.setRowHeight(40);
        jTableModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableModelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableModelos);

        jPanelFundo.add(jScrollPane1);
        jScrollPane1.setBounds(0, 430, 930, 200);

        jTextFieldDescricao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyTyped(evt);
            }
        });
        jPanelFundo.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(150, 190, 373, 22);

        jTextFieldIdentificador.setEditable(false);
        jTextFieldIdentificador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.add(jTextFieldIdentificador);
        jTextFieldIdentificador.setBounds(20, 190, 107, 22);

        jLabelIdentificador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelIdentificador.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdentificador.setText("Identificador");
        jPanelFundo.add(jLabelIdentificador);
        jLabelIdentificador.setBounds(20, 170, 86, 20);

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescricao.setText("Descrição");
        jPanelFundo.add(jLabelDescricao);
        jLabelDescricao.setBounds(150, 170, 92, 20);

        jTextFieldUrl.setEditable(false);
        jTextFieldUrl.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });
        jPanelFundo.add(jTextFieldUrl);
        jTextFieldUrl.setBounds(20, 240, 506, 22);

        jLabelUrl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUrl.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUrl.setText("URL");
        jPanelFundo.add(jLabelUrl);
        jLabelUrl.setBounds(20, 220, 26, 20);

        getContentPane().add(jPanelFundo);
        jPanelFundo.setBounds(0, 0, 930, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoKeyReleased

    private void jTextFieldDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyTyped
        char e = evt.getKeyChar();

        if (Character.isLowerCase(e)) {
            evt.setKeyChar(Character.toUpperCase(e));
        }
    }//GEN-LAST:event_jTextFieldDescricaoKeyTyped

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed

    }//GEN-LAST:event_jTextFieldUrlActionPerformed

    private void jLabelBotaoIncluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseMoved
         

        jLabelBotaoIncluir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluirencima.png");
        jLabelBotaoIncluir.setIcon(iconeIncluirMouse);

    }//GEN-LAST:event_jLabelBotaoIncluirMouseMoved

    private void jLabelBotaoIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseClicked
        ImageIcon iconlogo = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluirclicado.png");
        jLabelBotaoIncluir.setIcon(iconlogo);
       
        try {
           
            int idMarca = 0;
            objetoMarca.buscar(idMarca);
            Modelo objeto = new Modelo(0, jTextFieldDescricao.getText(), jTextFieldUrl.getText(), objetoMarca.buscar(idMarca));
            ArrayList<Marca> lista = objetoMarca.listagem();
            for(int i = 0; i < lista.size(); i++){
                if(jComboBoxMarca.getSelectedItem().equals(lista.get(i).getDescricao())){
                    objeto.setMarca(lista.get(i));
                }
            }
            modeloControle.nada(objeto);
            modeloControle.semFoto(objeto);
            modeloControle.mesmaFoto(objeto);            
            jTextFieldDescricao.setText("");
            modeloControle.incluir(objeto);
            imprimirDadosNaGrid(modeloControle.listagemModelo());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jLabelBotaoIncluirMouseClicked

    private void jLabelBotaoIncluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseExited
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluir.png");
        jLabelBotaoIncluir.setIcon(iconeIncluirMouse);
    }//GEN-LAST:event_jLabelBotaoIncluirMouseExited

    private void jLabelBotaoBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseMoved
        jLabelBotaoBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscarencima.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);
    }//GEN-LAST:event_jLabelBotaoBuscarMouseMoved

    private void jLabelBotaoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseClicked
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscarclicado.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);
        try {

            JFileChooser fc = new JFileChooser("./src/Imagens/imagesModelo");
            File workingDirectory = new File("./src/Imagens/imagesModelo");
            fc.setCurrentDirectory(workingDirectory);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            jTextFieldUrl.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            jLabelModelo.setIcon(iconLogo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this,"Nenhum arquivo selecionado");
        }
    }//GEN-LAST:event_jLabelBotaoBuscarMouseClicked

    private void jLabelBotaoBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseExited
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscar.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);
    }//GEN-LAST:event_jLabelBotaoBuscarMouseExited

    private void jLabelBotaoAlterarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseMoved
       jLabelBotaoAlterar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterarencima.png");
        jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterarMouseMoved

    private void jLabelBotaoAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseClicked
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterarclicado.png");
        jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
        try {
            int idMarca = 0;
            
            Modelo objetoAlterar = new Modelo(Integer.parseInt(jTextFieldIdentificador.getText()), jTextFieldDescricao.getText(), 
                   jTextFieldUrl.getText(), 
            objetoMarca.buscar(idMarca));
              ArrayList<Marca> lista = objetoMarca.listagem();
            for(int i = 0; i < lista.size(); i++){
                if(jComboBoxMarca.getSelectedItem().equals(lista.get(i).getDescricao())){
                    objetoAlterar.setMarca(lista.get(i));
                }
            }
           modeloControle.alterar(objetoAlterar);
            imprimirDadosNaGrid(modeloControle.listagemModelo());
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jLabelBotaoAlterarMouseClicked

    private void jLabelBotaoAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseExited
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterar.png");
        jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterarMouseExited

    private void jComboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaActionPerformed
         try {
             
             IMarcaControle objeto = new MarcaControle();
             ArrayList <Marca> lista = objeto.listagem();
             
             for(int i = 0;i < lista.size();i++){
             if( jComboBoxMarca.getSelectedItem().equals(lista.get(i).getDescricao())){
             ImageIcon iconlogo = new ImageIcon(lista.get(i).getUrl());    
             jLabelMarcaLogo.setIcon(iconlogo);
             }
             
             }

             
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Marca não existe");
         }
        
    }//GEN-LAST:event_jComboBoxMarcaActionPerformed

    private void jComboBoxMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMarcaMouseClicked
      
    }//GEN-LAST:event_jComboBoxMarcaMouseClicked

    private void jTableModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableModelosMouseClicked
        jTextFieldIdentificador.setText(jTableModelos.getValueAt(jTableModelos.getSelectedRow(), 0).toString());
        jTextFieldDescricao.setText(jTableModelos.getValueAt(jTableModelos.getSelectedRow(), 1).toString());
        jTextFieldUrl.setText(jTableModelos.getValueAt(jTableModelos.getSelectedRow(), 2).toString());
        jLabelModelo.setIcon((Icon) jTableModelos.getValueAt(jTableModelos.getSelectedRow(), 4));
        
    }//GEN-LAST:event_jTableModelosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JLabel jLabelBorda;
    private javax.swing.JLabel jLabelBorda1;
    private javax.swing.JLabel jLabelBotaoAlterar;
    private javax.swing.JLabel jLabelBotaoBuscar;
    private javax.swing.JLabel jLabelBotaoIncluir;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMarcaLogo;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelModeloVeiculo2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModelos;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
