package com.tllr.visao;

import com.tllr.codigoFuncionario.CODIGO;
import com.tllr.controle.ILoginControle;
import com.tllr.controle.LoginControle;
import com.tllr.modelos.Login;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Point;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Usuario
 */
public class TesteDeLogin extends javax.swing.JFrame {
        private Point point = new Point();
        ILoginControle loginControle = new LoginControle();
        
        

    /**
     * Creates new form TesteDeLogin
     */
    public TesteDeLogin() {
        initComponents();
        setBounds(0,0,1000,619);
        setLocationRelativeTo(null);
            try {
                loginControle.seNaoExistirId();
            } catch (Exception ex) {
                Logger.getLogger(TesteDeLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabelLogar = new javax.swing.JLabel();
        jLabelCadastrar = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        faleConosco = new javax.swing.JLabel();
        privacidadeDePolitica = new javax.swing.JLabel();
        redesSociais = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Login");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Senha");

        jCheckBox1.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Manter-me conectado?");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseExited(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabelLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/LOGAR2.png"))); // NOI18N
        jLabelLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelLogarMouseMoved(evt);
            }
        });
        jLabelLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLogarMouseExited(evt);
            }
        });

        jLabelCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/cadastro.png"))); // NOI18N
        jLabelCadastrar.setText("jLabel4");
        jLabelCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCadastrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelCadastrarMouseMoved(evt);
            }
        });
        jLabelCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCadastrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCadastrarMouseExited(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bem vindo(a)!");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Esqueci a senha");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(jLabelLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(750, 0, 250, 620);

        faleConosco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        faleConosco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faleConoscoMouseClicked(evt);
            }
        });
        getContentPane().add(faleConosco);
        faleConosco.setBounds(150, 590, 130, 20);

        privacidadeDePolitica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        privacidadeDePolitica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                privacidadeDePoliticaMouseClicked(evt);
            }
        });
        getContentPane().add(privacidadeDePolitica);
        privacidadeDePolitica.setBounds(300, 590, 190, 20);

        redesSociais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redesSociais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redesSociaisMouseClicked(evt);
            }
        });
        getContentPane().add(redesSociais);
        redesSociais.setBounds(27, 590, 100, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/Tela de login beta (1).png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 750, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    private void jLabelLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogarMouseClicked
        ImageIcon logar = new ImageIcon("./src/Imagens/ImageAnimacoes/LOGARSuavizado.png");
        jLabelLogar.setIcon(logar);
        Point p = this.getLocation();
        TesteDeLogin testeDeLogin2 = this;
        try {
            Login objetoLogin = new Login(0, jTextField1.getText(), jPasswordField1.getText(),"");
           

            if( loginControle.achar(objetoLogin) == true){
                this.dispose();
                JOptionPane.showMessageDialog(this, loginControle.liberar(objetoLogin));
            }
            else{
                                  new Thread(){
            @Override
            public void run() {
                    try {
                         for (int i = 0; i<6; i++){
                    testeDeLogin2.setLocation(p.x-10,p.y);
                        sleep(20);
                        testeDeLogin2.setLocation(p.x+10,p.y);
                        sleep(20);
                    } 
                         testeDeLogin2.setLocation(p.x,p.y);
                    }catch (InterruptedException ex) {
                        Logger.getLogger(TesteDeLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }.start();

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
   
    }//GEN-LAST:event_jLabelLogarMouseClicked

    private void jCheckBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseEntered
        jCheckBox1.setForeground(new Color(255, 255, 255));
       
    }//GEN-LAST:event_jCheckBox1MouseEntered

    private void jCheckBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseExited
        jCheckBox1.setForeground(new Color(0,0,0));
        
    }//GEN-LAST:event_jCheckBox1MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(new Color(255, 255, 255));
        
        
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(new Color(0,0,0));
        jLabel7.setText("Esqueci a senha");
       
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void redesSociaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redesSociaisMouseClicked
        try {
         
        Desktop.getDesktop().browse(new URI("http://www.google.com"));
         
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
    }
    }//GEN-LAST:event_redesSociaisMouseClicked

    private void faleConoscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faleConoscoMouseClicked
        try {
         
        Desktop.getDesktop().browse(new URI("http://www.google.com"));
         
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
    }
    }//GEN-LAST:event_faleConoscoMouseClicked

    private void privacidadeDePoliticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privacidadeDePoliticaMouseClicked
        try {
         
        Desktop.getDesktop().browse(new URI("http://www.google.com"));
         
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
    }
    }//GEN-LAST:event_privacidadeDePoliticaMouseClicked

    private void jLabelCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCadastrarMouseClicked
                ImageIcon botaoCadastrar = new ImageIcon("./src/Imagens/ImageAnimacoes/cadastroLuminoso.png");
                jLabelCadastrar.setIcon(botaoCadastrar);
        CODIGO senha = new CODIGO();
          try{ 
            senha.incluir();
            this.dispose();
            TelaVerificacao chamar = new TelaVerificacao();
            chamar.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TesteDeLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabelCadastrarMouseClicked

    private void jLabelLogarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogarMouseMoved
        ImageIcon botaoLogar = new ImageIcon("./src/Imagens/ImageAnimacoes/LOGARLuminoso.png");
        jLabelLogar.setIcon(botaoLogar);
    }//GEN-LAST:event_jLabelLogarMouseMoved

    private void jLabelLogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogarMouseExited

        ImageIcon botaoLogar = new ImageIcon("./src/Imagens/Images/LOGAR2.png");
        jLabelLogar.setIcon(botaoLogar);

    }//GEN-LAST:event_jLabelLogarMouseExited

    private void jLabelCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCadastrarMouseExited
         ImageIcon botaoCadastrar = new ImageIcon("./src/Imagens/Images/cadastro.png");
        jLabelCadastrar.setIcon(botaoCadastrar);
    }//GEN-LAST:event_jLabelCadastrarMouseExited

    private void jLabelCadastrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCadastrarMouseMoved
     ImageIcon botaoCadastrar = new ImageIcon("./src/Imagens/ImageAnimacoes/cadastroLuminoso.png");
     jLabelCadastrar.setIcon(botaoCadastrar);

    }//GEN-LAST:event_jLabelCadastrarMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteDeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel faleConosco;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCadastrar;
    private javax.swing.JLabel jLabelLogar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel privacidadeDePolitica;
    private javax.swing.JLabel redesSociais;
    // End of variables declaration//GEN-END:variables
}
