/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.tllr.telasReservas;

import com.tllr.visao.*;
import com.tllr.controle.IMarcaControle;
import com.tllr.controle.MarcaControle;
import com.tllr.imagensnatabela.JTableRenderer;
import com.tllr.modelos.Marca;
import java.awt.Cursor;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiago
 */
public class TelaDeCadastroMarcas extends javax.swing.JInternalFrame {
        IMarcaControle marcaControle = new MarcaControle();
    /**
     * Creates new form TelaDeCadastroMarcas
     */
    public TelaDeCadastroMarcas() {
        initComponents();
        jTextFieldIdentificador.setEnabled(false);
        jTextFieldUrl.setEnabled(false);
               setBounds(0,0,920,620);

        try {
            imprimirDadosNaGrid(marcaControle.listagem());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelfundo = new javax.swing.JPanel();
        jLabelBotaoBuscar = new javax.swing.JLabel();
        jLabelIdentificador = new javax.swing.JLabel();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelBotaoIncluir = new javax.swing.JLabel();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMarcas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanelTopo = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelBotaoAlterar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jPanelfundo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelfundo.setLayout(null);

        jLabelBotaoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botao buscar normal.png"))); // NOI18N
        jLabelBotaoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseMoved(evt);
            }
        });
        jLabelBotaoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoBuscarMouseExited(evt);
            }
        });
        jPanelfundo.add(jLabelBotaoBuscar);
        jLabelBotaoBuscar.setBounds(670, 340, 93, 43);

        jLabelIdentificador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelIdentificador.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIdentificador.setText("Identificador");
        jPanelfundo.add(jLabelIdentificador);
        jLabelIdentificador.setBounds(20, 142, 86, 20);

        jTextFieldIdentificador.setEditable(false);
        jTextFieldIdentificador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelfundo.add(jTextFieldIdentificador);
        jTextFieldIdentificador.setBounds(20, 168, 107, 22);

        jTextFieldDescricao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyTyped(evt);
            }
        });
        jPanelfundo.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(139, 168, 373, 22);
        jPanelfundo.add(jLabel2);
        jLabel2.setBounds(1622, 228, 123, 0);

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescricao.setText("Descrição");
        jPanelfundo.add(jLabelDescricao);
        jLabelDescricao.setBounds(139, 142, 65, 20);

        jLabelBotaoIncluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botao incluir normal.png"))); // NOI18N
        jLabelBotaoIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoIncluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseMoved(evt);
            }
        });
        jLabelBotaoIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoIncluirMouseExited(evt);
            }
        });
        jPanelfundo.add(jLabelBotaoIncluir);
        jLabelBotaoIncluir.setBounds(20, 295, 90, 40);

        jLabelUrl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUrl.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUrl.setText("URL");
        jPanelfundo.add(jLabelUrl);
        jLabelUrl.setBounds(20, 228, 26, 20);

        jTextFieldUrl.setEditable(false);
        jTextFieldUrl.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });
        jPanelfundo.add(jTextFieldUrl);
        jTextFieldUrl.setBounds(20, 254, 492, 22);

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelfundo.add(jLabelLogo);
        jLabelLogo.setBounds(690, 220, 70, 60);

        jTableMarcas.setAutoCreateRowSorter(true);
        jTableMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descricao", "Url", "Logo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMarcas.setRowHeight(40);
        jTableMarcas.setUpdateSelectionOnSort(false);
        jTableMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMarcasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMarcas);
        if (jTableMarcas.getColumnModel().getColumnCount() > 0) {
            jTableMarcas.getColumnModel().getColumn(3).setCellRenderer(new JTableRenderer());
        }

        jPanelfundo.add(jScrollPane1);
        jScrollPane1.setBounds(0, 380, 910, 200);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("BOTÃO ALTERAR");
        jPanelfundo.add(jLabel9);
        jLabel9.setBounds(1400, 637, 95, 16);

        jPanelTopo.setBackground(new java.awt.Color(0, 0, 51));

        jLabelEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/designed2.png"))); // NOI18N

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastro de veículos");

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(846, Short.MAX_VALUE))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelfundo.add(jPanelTopo);
        jPanelTopo.setBounds(0, 0, 1739, 130);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("BOTÃO ATUALIZAR");
        jPanelfundo.add(jLabel10);
        jLabel10.setBounds(1252, 637, 109, 16);

        jLabelBotaoAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBotaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/botaoalterar.png"))); // NOI18N
        jLabelBotaoAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelBotaoAlterar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseMoved(evt);
            }
        });
        jLabelBotaoAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBotaoAlterarMouseExited(evt);
            }
        });
        jPanelfundo.add(jLabelBotaoAlterar);
        jLabelBotaoAlterar.setBounds(128, 295, 90, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Images/borda.png"))); // NOI18N
        jPanelfundo.add(jLabel3);
        jLabel3.setBounds(680, 200, 100, 100);

        jLabelLogo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelLogo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLogo1.setText("Logo");
        jPanelfundo.add(jLabelLogo1);
        jLabelLogo1.setBounds(700, 160, 60, 32);

        getContentPane().add(jPanelfundo);
        jPanelfundo.setBounds(-4, 0, 910, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void imprimirDadosNaGrid(ArrayList<Marca> listaDeMarcas) {
        try {

            DefaultTableModel model = (DefaultTableModel) jTableMarcas.getModel();
            
            

            //Limpa a tabela 
            Collections.sort(listaDeMarcas);
            model.setNumRows(0);
            Iterator<Marca> lista = listaDeMarcas.iterator();               

            while (lista.hasNext()) {
                String[] saida = new String[3];
                Marca aux = lista.next();
                saida[0] = aux.getId() + "";
                saida[1] = aux.getDescricao();
                saida[2] = aux.getUrl();
                
                //Incluir nova linha na Tabela
                model.addRow(saida);
                
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }
    private void jLabelBotaoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseClicked
         ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscarclicado.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);    
        try {
            
            JFileChooser fc = new JFileChooser("./src/Imagens/imagesLogo");
            File workingDirectory = new File("./src/Imagens/imagesLogo");
            fc.setCurrentDirectory(workingDirectory);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            jTextFieldUrl.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            jLabelLogo.setIcon(iconLogo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this,"Nenhum arquivo selecionado");
        }

    }//GEN-LAST:event_jLabelBotaoBuscarMouseClicked

    private void jTextFieldDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyReleased
       

    }//GEN-LAST:event_jTextFieldDescricaoKeyReleased

    private void jTextFieldDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyTyped
        char e = evt.getKeyChar();

        if (!Character.isLetter(e)) {
            evt.consume();
        }

        if (Character.isLowerCase(e)) {
            evt.setKeyChar(Character.toUpperCase(e));
        }
    }//GEN-LAST:event_jTextFieldDescricaoKeyTyped

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed

    }//GEN-LAST:event_jTextFieldUrlActionPerformed

    private void jTableMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMarcasMouseClicked
        jTextFieldIdentificador.setText(jTableMarcas.getValueAt(jTableMarcas.getSelectedRow(), 0).toString());
        jTextFieldDescricao.setText(jTableMarcas.getValueAt(jTableMarcas.getSelectedRow(), 1).toString());
        jTextFieldUrl.setText(jTableMarcas.getValueAt(jTableMarcas.getSelectedRow(), 2).toString());
        String nome = jTextFieldUrl.getText();
        ImageIcon logo = new ImageIcon(nome);
        jLabelLogo.setIcon(logo);
        
        
        
        
        
    }//GEN-LAST:event_jTableMarcasMouseClicked

    private void jLabelBotaoIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseClicked
        ImageIcon iconlogo = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluirclicado.png");
        jLabelBotaoIncluir.setIcon(iconlogo);
        try {
            File path = new File(jTextFieldUrl.getText());
            String logo  = "./src/Imagens/imagesLogo/" + path.getName();
            
            
            Marca objeto = new Marca(0, jTextFieldDescricao.getText(), logo);
            marcaControle.nada(objeto);
            marcaControle.semFoto(objeto);
            marcaControle.mesmaFoto(objeto);
            marcaControle.incluir(objeto);
            jTextFieldDescricao.setText("");
            imprimirDadosNaGrid(marcaControle.listagem());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jLabelBotaoIncluirMouseClicked

    private void jLabelBotaoIncluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseMoved
         jLabelBotaoIncluir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluirencima.png");
        jLabelBotaoIncluir.setIcon(iconeIncluirMouse);


    }//GEN-LAST:event_jLabelBotaoIncluirMouseMoved

    private void jLabelBotaoIncluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoIncluirMouseExited
        ImageIcon iconeIncluirMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoincluir.png");
        jLabelBotaoIncluir.setIcon(iconeIncluirMouse);

    }//GEN-LAST:event_jLabelBotaoIncluirMouseExited

    private void jLabelBotaoBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseMoved
        jLabelBotaoBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscarencima.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);       
    }//GEN-LAST:event_jLabelBotaoBuscarMouseMoved

    private void jLabelBotaoBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoBuscarMouseExited
        ImageIcon iconeBuscarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaobuscar.png");
        jLabelBotaoBuscar.setIcon(iconeBuscarMouse);       

    }//GEN-LAST:event_jLabelBotaoBuscarMouseExited

    private void jLabelBotaoAlterarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseMoved
        jLabelBotaoAlterar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterarencima.png");
        jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterarMouseMoved

    private void jLabelBotaoAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoAlterarMouseExited
       ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterar.png");
        jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
    }//GEN-LAST:event_jLabelBotaoAlterarMouseExited

    private void jLabelBotaoAlterarMouseClicked(java.awt.event.MouseEvent evt) {                                                
            try {
                ImageIcon iconeAlterarMouse = new ImageIcon("./src/Imagens/ImageAnimacoes/botaoalterarclicado.png");
                jLabelBotaoAlterar.setIcon(iconeAlterarMouse);
                Marca objetoAlterar = new Marca(Integer.parseInt(jTextFieldIdentificador.getText()), jTextFieldDescricao.getText(), jTextFieldUrl.getText());
                marcaControle.alterar(objetoAlterar);
                imprimirDadosNaGrid(marcaControle.listagem());
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    
    }          
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBotaoAlterar;
    private javax.swing.JLabel jLabelBotaoBuscar;
    private javax.swing.JLabel jLabelBotaoIncluir;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JPanel jPanelfundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMarcas;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables

  
}
